### ISSUE TITLE
Añadirse al canal de Slack

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-para-desarrolladores-web_ed10#3]
Hola a tod@s!

Para añadirse al canal de Slack de OSW lo más fácil es autoinvitaros en este [link](https://slack.osweekends.com).

Pasarme el nick por aquí y os añado a un canal privado. 😸

**Comment by Craftmeet** [comment]
Craftmeet

**Comment by ACagigas** [comment]
Hola! Soy Andrea, escribo para avisaros que voy a llegar unos 10 minutos tarde :( estoy en el metro de camino. Lo sientoo.

**Comment by ACagigas** [comment]
Hola! Soy Andrea, escribo para avisaros que voy a llegar unos 10 minutos tarde :( estoy en el metro de camino. Lo sientoo.

**Comment by UlisesGascon** [comment]
Gracias por avisar @ACagigas! Te esperamos :-)

**Comment by Serchx** [comment]
Hola Ulises, no se si te tengo que decir por aquí que me metas en slack, tengo un lío, jajajaja

Saludos u buen finde a todos

**Comment by UlisesGascon** [comment]
@Serchx te dejo el link.. https://slack.osweekends.com/ es una invitación directa ;-)
